name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install npm packages
        run: npm install
      - name: Run main file
        run: ./node_modules/.bin/ts-node main.ts
